rootProject.name = "java-labs"
include("Lab1")
include("Lab2")
include(":Lab2:DataAccess")
include(":Lab2:Application")
include(":Lab2:Presentation")
include("Lab3")
include(":Lab3:DataAccess")
include(":Lab3:Application")
include(":Lab3:Presentation")
include("Lab4")
include(":Lab4:DataAccess")
include(":Lab4:Application")
include(":Lab4:Presentation")